# Generated by Django 5.2.1 on 2025-06-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_picture_liked_alter_picture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/profile.svg', upload_to='images/avatars/'),
        ),
    ]
