# Generated by Django 5.2.10 on 2026-01-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/profile.svg', upload_to='avatars/'),
        ),
    ]
